#!/usr/bin/env python3
import re
from pathlib import Path


def get_serial():
    cpuinfo = Path('/proc/cpuinfo').read_text()
    # Serial          : 00000000413c11de
    for line in cpuinfo.splitlines():
        if 'Serial' in line:
            return line.strip().split(':')[1].strip()[8:]


def set_ap():
    hostapd_conf = Path('/etc/hostapd/hostapd.conf')
    try:
        new_config = re.sub(r'^ssid=(.*)', f'ssid=Akku_{get_serial()}', hostapd_conf.read_text(), flags=re.MULTILINE)
    except:
        pass
    else:
        if new_config:
            hostapd_conf.write_text(new_config)


if __name__ == '__main__':
    set_ap()

